import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { QueryProvider } from '@/components/query-provider'

import './globals.css'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Next Jira Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased min-h-screen`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
